### ISSUE TITLE
Broken not helper

### ISSUE THREAD

**Issue by killercup** [killercup/handlebars-helpers-rust#1]
Apparently, the param that contains the result from the subexpression `(gt 5 3)` is of type `String("true")` instead of `Bool(true)`. This means the `not` helper doesn't work.

- - -

This test

```rust
extern crate handlebars;
extern crate handlebars_helpers;
#[macro_use] extern crate serde_json;

use handlebars::Handlebars;

#[test]
fn nested_conditions() {
    let mut handlebars = Handlebars::new();
    handlebars_helpers::register(&mut handlebars);

    let result = handlebars.template_render(
        "{{#if (not (gt 5 3))}}lorem{{else}}ipsum{{/if}}", &json!({})
    ).unwrap();
    assert_eq!(&result, "ipsum");
}
```

fails with

```
…
test nested_conditions ... FAILED

failures:

---- nested_conditions stdout ----
        debug!! gt(x, y, ): true
thread 'nested_conditions' panicked at 'called `Result::unwrap()` on an `Err` value: RenderError(RenderError { desc: "`not` helper: Couldn\'t convert parameter x to type `bool`. It\'s String(\"true\") as JSON. Got these params: [ContextJson { path: None, value: String(\"true\") }]", template_name: None, line_no: None, column_no: None, cause: None })', src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
…
```

**Comment by sunng87** [comment]
Hi @killercup , just verified behaviour of both handlebars-rust and original js implementation. The result of subexpression is treated as **JSON string literal**. So for `gt`, if we want to return false, we can just skip writing things. Writing `false` is actually `"false"` for handlebars.

I have a few subexpression tests. We may need to consider multiple cases for `not`:
https://github.com/sunng87/handlebars-rust/blob/master/tests/subexpression.rs

**Comment by killercup** [comment]
> The result of subexpression is treated as JSON string literal.

Does that mean we loose type information when using subexpressions? So, `(add 1 2)` would result in `"3"`? That would be weird. Would it make sense to try and deserialize the params and fall back to treating them as string if that fails?

In general, I'm also not sure if 100% JS compatibility is really important in this case, as all the helpers will need to be rewritten anyway.

**Comment by sunng87** [comment]
Hmmm… the JS implementation can return a non-string value. I will find a way to fix it from handlebars-rust.
