### ISSUE TITLE
Merge this macro into handlebars-rust

### ISSUE THREAD

**Issue by sunng87** [killercup/handlebars-helpers-rust#4]
hi @killercup , I found this macro very helpful for helper development. However, it's still not in crates.io and as helper API evolving we need to keep it maintained. I wish we can put it into the core of handlebars-rust to benefit helper developers. 

If you agree, could you please make a pull request to [handlebars-rust](http://github.com/sunng87/handlebars-rust) and I will merge.

**Comment by killercup** [comment]
Hi @sunng87, I'd be happy to have this part of handlebars-rust! I'll try to make a PR shortly.

**Comment by sunng87** [comment]
Thanks! @killercup
